apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-app
  labels:
    app: random-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-app
  template:
    metadata:
      labels:
        app: random-app
    spec:
      containers:
      - name: random-app-container
        image: nginx:latest
        ports:
        - containerPort: 80
